/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as rootLayoutRouteRouteImport } from './routes/(root-layout)/route'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as rootLayoutIndexRouteImport } from './routes/(root-layout)/index'
import { Route as rootLayoutAboutIndexRouteImport } from './routes/(root-layout)/about/index'
import { Route as rootLayoutMerchIndexRouteImport } from './routes/(root-layout)/merch/index'
import { Route as rootLayoutModelsIndexRouteImport } from './routes/(root-layout)/models/index'
import { Route as rootLayoutPrivacyPolicyIndexRouteImport } from './routes/(root-layout)/privacy-policy/index'
import { Route as rootLayoutTermsOfServiceIndexRouteImport } from './routes/(root-layout)/terms-of-service/index'
import { Route as rootLayoutModelsEdgeIndexRouteImport } from './routes/(root-layout)/models/edge/index'
import { Route as rootLayoutModelsFuerzaIndexRouteImport } from './routes/(root-layout)/models/fuerza/index'
import { Route as rootLayoutModelsTerrenoIndexRouteImport } from './routes/(root-layout)/models/terreno/index'

const rootLayoutRouteRoute = rootLayoutRouteRouteImport.update({
  id: '/(root-layout)',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const rootLayoutIndexRoute = rootLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootLayoutRouteRoute,
} as any)
const rootLayoutAboutIndexRoute = rootLayoutAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootLayoutRouteRoute,
} as any)
const rootLayoutMerchIndexRoute = rootLayoutMerchIndexRouteImport.update({
  id: '/merch/',
  path: '/merch/',
  getParentRoute: () => rootLayoutRouteRoute,
} as any)
const rootLayoutModelsIndexRoute = rootLayoutModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => rootLayoutRouteRoute,
} as any)
const rootLayoutPrivacyPolicyIndexRoute =
  rootLayoutPrivacyPolicyIndexRouteImport.update({
    id: '/privacy-policy/',
    path: '/privacy-policy/',
    getParentRoute: () => rootLayoutRouteRoute,
  } as any)
const rootLayoutTermsOfServiceIndexRoute =
  rootLayoutTermsOfServiceIndexRouteImport.update({
    id: '/terms-of-service/',
    path: '/terms-of-service/',
    getParentRoute: () => rootLayoutRouteRoute,
  } as any)
const rootLayoutModelsEdgeIndexRoute =
  rootLayoutModelsEdgeIndexRouteImport.update({
    id: '/models/edge/',
    path: '/models/edge/',
    getParentRoute: () => rootLayoutRouteRoute,
  } as any)
const rootLayoutModelsFuerzaIndexRoute =
  rootLayoutModelsFuerzaIndexRouteImport.update({
    id: '/models/fuerza/',
    path: '/models/fuerza/',
    getParentRoute: () => rootLayoutRouteRoute,
  } as any)
const rootLayoutModelsTerrenoIndexRoute =
  rootLayoutModelsTerrenoIndexRouteImport.update({
    id: '/models/terreno/',
    path: '/models/terreno/',
    getParentRoute: () => rootLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/': typeof rootLayoutIndexRoute
  '/about/': typeof rootLayoutAboutIndexRoute
  '/merch/': typeof rootLayoutMerchIndexRoute
  '/models/': typeof rootLayoutModelsIndexRoute
  '/privacy-policy/': typeof rootLayoutPrivacyPolicyIndexRoute
  '/terms-of-service/': typeof rootLayoutTermsOfServiceIndexRoute
  '/models/edge/': typeof rootLayoutModelsEdgeIndexRoute
  '/models/fuerza/': typeof rootLayoutModelsFuerzaIndexRoute
  '/models/terreno/': typeof rootLayoutModelsTerrenoIndexRoute
}
export interface FileRoutesByTo {
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/': typeof rootLayoutIndexRoute
  '/about': typeof rootLayoutAboutIndexRoute
  '/merch': typeof rootLayoutMerchIndexRoute
  '/models': typeof rootLayoutModelsIndexRoute
  '/privacy-policy': typeof rootLayoutPrivacyPolicyIndexRoute
  '/terms-of-service': typeof rootLayoutTermsOfServiceIndexRoute
  '/models/edge': typeof rootLayoutModelsEdgeIndexRoute
  '/models/fuerza': typeof rootLayoutModelsFuerzaIndexRoute
  '/models/terreno': typeof rootLayoutModelsTerrenoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(root-layout)': typeof rootLayoutRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/(root-layout)/': typeof rootLayoutIndexRoute
  '/(root-layout)/about/': typeof rootLayoutAboutIndexRoute
  '/(root-layout)/merch/': typeof rootLayoutMerchIndexRoute
  '/(root-layout)/models/': typeof rootLayoutModelsIndexRoute
  '/(root-layout)/privacy-policy/': typeof rootLayoutPrivacyPolicyIndexRoute
  '/(root-layout)/terms-of-service/': typeof rootLayoutTermsOfServiceIndexRoute
  '/(root-layout)/models/edge/': typeof rootLayoutModelsEdgeIndexRoute
  '/(root-layout)/models/fuerza/': typeof rootLayoutModelsFuerzaIndexRoute
  '/(root-layout)/models/terreno/': typeof rootLayoutModelsTerrenoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/robots.txt'
    | '/sitemap.xml'
    | '/'
    | '/about/'
    | '/merch/'
    | '/models/'
    | '/privacy-policy/'
    | '/terms-of-service/'
    | '/models/edge/'
    | '/models/fuerza/'
    | '/models/terreno/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/robots.txt'
    | '/sitemap.xml'
    | '/'
    | '/about'
    | '/merch'
    | '/models'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/models/edge'
    | '/models/fuerza'
    | '/models/terreno'
  id:
    | '__root__'
    | '/(root-layout)'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/(root-layout)/'
    | '/(root-layout)/about/'
    | '/(root-layout)/merch/'
    | '/(root-layout)/models/'
    | '/(root-layout)/privacy-policy/'
    | '/(root-layout)/terms-of-service/'
    | '/(root-layout)/models/edge/'
    | '/(root-layout)/models/fuerza/'
    | '/(root-layout)/models/terreno/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  rootLayoutRouteRoute: typeof rootLayoutRouteRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(root-layout)': {
      id: '/(root-layout)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof rootLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(root-layout)/': {
      id: '/(root-layout)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof rootLayoutIndexRouteImport
      parentRoute: typeof rootLayoutRouteRoute
    }
    '/(root-layout)/about/': {
      id: '/(root-layout)/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof rootLayoutAboutIndexRouteImport
      parentRoute: typeof rootLayoutRouteRoute
    }
    '/(root-layout)/merch/': {
      id: '/(root-layout)/merch/'
      path: '/merch'
      fullPath: '/merch/'
      preLoaderRoute: typeof rootLayoutMerchIndexRouteImport
      parentRoute: typeof rootLayoutRouteRoute
    }
    '/(root-layout)/models/': {
      id: '/(root-layout)/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof rootLayoutModelsIndexRouteImport
      parentRoute: typeof rootLayoutRouteRoute
    }
    '/(root-layout)/privacy-policy/': {
      id: '/(root-layout)/privacy-policy/'
      path: '/privacy-policy'
      fullPath: '/privacy-policy/'
      preLoaderRoute: typeof rootLayoutPrivacyPolicyIndexRouteImport
      parentRoute: typeof rootLayoutRouteRoute
    }
    '/(root-layout)/terms-of-service/': {
      id: '/(root-layout)/terms-of-service/'
      path: '/terms-of-service'
      fullPath: '/terms-of-service/'
      preLoaderRoute: typeof rootLayoutTermsOfServiceIndexRouteImport
      parentRoute: typeof rootLayoutRouteRoute
    }
    '/(root-layout)/models/edge/': {
      id: '/(root-layout)/models/edge/'
      path: '/models/edge'
      fullPath: '/models/edge/'
      preLoaderRoute: typeof rootLayoutModelsEdgeIndexRouteImport
      parentRoute: typeof rootLayoutRouteRoute
    }
    '/(root-layout)/models/fuerza/': {
      id: '/(root-layout)/models/fuerza/'
      path: '/models/fuerza'
      fullPath: '/models/fuerza/'
      preLoaderRoute: typeof rootLayoutModelsFuerzaIndexRouteImport
      parentRoute: typeof rootLayoutRouteRoute
    }
    '/(root-layout)/models/terreno/': {
      id: '/(root-layout)/models/terreno/'
      path: '/models/terreno'
      fullPath: '/models/terreno/'
      preLoaderRoute: typeof rootLayoutModelsTerrenoIndexRouteImport
      parentRoute: typeof rootLayoutRouteRoute
    }
  }
}

interface rootLayoutRouteRouteChildren {
  rootLayoutIndexRoute: typeof rootLayoutIndexRoute
  rootLayoutAboutIndexRoute: typeof rootLayoutAboutIndexRoute
  rootLayoutMerchIndexRoute: typeof rootLayoutMerchIndexRoute
  rootLayoutModelsIndexRoute: typeof rootLayoutModelsIndexRoute
  rootLayoutPrivacyPolicyIndexRoute: typeof rootLayoutPrivacyPolicyIndexRoute
  rootLayoutTermsOfServiceIndexRoute: typeof rootLayoutTermsOfServiceIndexRoute
  rootLayoutModelsEdgeIndexRoute: typeof rootLayoutModelsEdgeIndexRoute
  rootLayoutModelsFuerzaIndexRoute: typeof rootLayoutModelsFuerzaIndexRoute
  rootLayoutModelsTerrenoIndexRoute: typeof rootLayoutModelsTerrenoIndexRoute
}

const rootLayoutRouteRouteChildren: rootLayoutRouteRouteChildren = {
  rootLayoutIndexRoute: rootLayoutIndexRoute,
  rootLayoutAboutIndexRoute: rootLayoutAboutIndexRoute,
  rootLayoutMerchIndexRoute: rootLayoutMerchIndexRoute,
  rootLayoutModelsIndexRoute: rootLayoutModelsIndexRoute,
  rootLayoutPrivacyPolicyIndexRoute: rootLayoutPrivacyPolicyIndexRoute,
  rootLayoutTermsOfServiceIndexRoute: rootLayoutTermsOfServiceIndexRoute,
  rootLayoutModelsEdgeIndexRoute: rootLayoutModelsEdgeIndexRoute,
  rootLayoutModelsFuerzaIndexRoute: rootLayoutModelsFuerzaIndexRoute,
  rootLayoutModelsTerrenoIndexRoute: rootLayoutModelsTerrenoIndexRoute,
}

const rootLayoutRouteRouteWithChildren = rootLayoutRouteRoute._addFileChildren(
  rootLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  rootLayoutRouteRoute: rootLayoutRouteRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
