/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as rootLayoutRouteRouteImport } from './routes/(root-layout)/route'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as rootLayoutIndexRouteImport } from './routes/(root-layout)/index'
import { Route as rootLayoutPrivacyPolicyIndexRouteImport } from './routes/(root-layout)/privacy-policy/index'
import { Route as rootLayoutTermsOfServiceIndexRouteImport } from './routes/(root-layout)/terms-of-service/index'
import { Route as rootLayoutLabGsapHeroIndexRouteImport } from './routes/(root-layout)/lab/gsap-hero/index'

const rootLayoutRouteRoute = rootLayoutRouteRouteImport.update({
  id: '/(root-layout)',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const rootLayoutIndexRoute = rootLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootLayoutRouteRoute,
} as any)
const rootLayoutPrivacyPolicyIndexRoute =
  rootLayoutPrivacyPolicyIndexRouteImport.update({
    id: '/privacy-policy/',
    path: '/privacy-policy/',
    getParentRoute: () => rootLayoutRouteRoute,
  } as any)
const rootLayoutTermsOfServiceIndexRoute =
  rootLayoutTermsOfServiceIndexRouteImport.update({
    id: '/terms-of-service/',
    path: '/terms-of-service/',
    getParentRoute: () => rootLayoutRouteRoute,
  } as any)
const rootLayoutLabGsapHeroIndexRoute =
  rootLayoutLabGsapHeroIndexRouteImport.update({
    id: '/lab/gsap-hero/',
    path: '/lab/gsap-hero/',
    getParentRoute: () => rootLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/': typeof rootLayoutIndexRoute
  '/privacy-policy/': typeof rootLayoutPrivacyPolicyIndexRoute
  '/terms-of-service/': typeof rootLayoutTermsOfServiceIndexRoute
  '/lab/gsap-hero/': typeof rootLayoutLabGsapHeroIndexRoute
}
export interface FileRoutesByTo {
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/': typeof rootLayoutIndexRoute
  '/privacy-policy': typeof rootLayoutPrivacyPolicyIndexRoute
  '/terms-of-service': typeof rootLayoutTermsOfServiceIndexRoute
  '/lab/gsap-hero': typeof rootLayoutLabGsapHeroIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(root-layout)': typeof rootLayoutRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/(root-layout)/': typeof rootLayoutIndexRoute
  '/(root-layout)/privacy-policy/': typeof rootLayoutPrivacyPolicyIndexRoute
  '/(root-layout)/terms-of-service/': typeof rootLayoutTermsOfServiceIndexRoute
  '/(root-layout)/lab/gsap-hero/': typeof rootLayoutLabGsapHeroIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/robots.txt'
    | '/sitemap.xml'
    | '/'
    | '/privacy-policy/'
    | '/terms-of-service/'
    | '/lab/gsap-hero/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/robots.txt'
    | '/sitemap.xml'
    | '/'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/lab/gsap-hero'
  id:
    | '__root__'
    | '/(root-layout)'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/(root-layout)/'
    | '/(root-layout)/privacy-policy/'
    | '/(root-layout)/terms-of-service/'
    | '/(root-layout)/lab/gsap-hero/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  rootLayoutRouteRoute: typeof rootLayoutRouteRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(root-layout)': {
      id: '/(root-layout)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof rootLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(root-layout)/': {
      id: '/(root-layout)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof rootLayoutIndexRouteImport
      parentRoute: typeof rootLayoutRouteRoute
    }
    '/(root-layout)/privacy-policy/': {
      id: '/(root-layout)/privacy-policy/'
      path: '/privacy-policy'
      fullPath: '/privacy-policy/'
      preLoaderRoute: typeof rootLayoutPrivacyPolicyIndexRouteImport
      parentRoute: typeof rootLayoutRouteRoute
    }
    '/(root-layout)/terms-of-service/': {
      id: '/(root-layout)/terms-of-service/'
      path: '/terms-of-service'
      fullPath: '/terms-of-service/'
      preLoaderRoute: typeof rootLayoutTermsOfServiceIndexRouteImport
      parentRoute: typeof rootLayoutRouteRoute
    }
    '/(root-layout)/lab/gsap-hero/': {
      id: '/(root-layout)/lab/gsap-hero/'
      path: '/lab/gsap-hero'
      fullPath: '/lab/gsap-hero/'
      preLoaderRoute: typeof rootLayoutLabGsapHeroIndexRouteImport
      parentRoute: typeof rootLayoutRouteRoute
    }
  }
}

interface rootLayoutRouteRouteChildren {
  rootLayoutIndexRoute: typeof rootLayoutIndexRoute
  rootLayoutPrivacyPolicyIndexRoute: typeof rootLayoutPrivacyPolicyIndexRoute
  rootLayoutTermsOfServiceIndexRoute: typeof rootLayoutTermsOfServiceIndexRoute
  rootLayoutLabGsapHeroIndexRoute: typeof rootLayoutLabGsapHeroIndexRoute
}

const rootLayoutRouteRouteChildren: rootLayoutRouteRouteChildren = {
  rootLayoutIndexRoute: rootLayoutIndexRoute,
  rootLayoutPrivacyPolicyIndexRoute: rootLayoutPrivacyPolicyIndexRoute,
  rootLayoutTermsOfServiceIndexRoute: rootLayoutTermsOfServiceIndexRoute,
  rootLayoutLabGsapHeroIndexRoute: rootLayoutLabGsapHeroIndexRoute,
}

const rootLayoutRouteRouteWithChildren = rootLayoutRouteRoute._addFileChildren(
  rootLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  rootLayoutRouteRoute: rootLayoutRouteRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
